CREATE TABLE IF NOT EXISTS "users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "email" text UNIQUE NOT NULL,
  "datetime_registered" timestamptz NOT NULL,
  "last_login" timestamptz
);

CREATE TABLE IF NOT EXISTS "passwords" (
  "password_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "user_id" integer NOT NULL,
  "salt" text NOT NULL,
  "password_hash" text NOT NULL,
  "password_last_updated" timestamptz
);

CREATE TABLE IF NOT EXISTS "sessions" (
  "session_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "user_id" integer NOT NULL,
  "login_time" timestamptz NOT NULL,
  "logout_time" timestamptz
);

CREATE TABLE IF NOT EXISTS "lkp_security_questions" (
  "security_question_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "security_question_text" text NOT NULL
);

CREATE TABLE IF NOT EXISTS "user_security_qs_as" (
  "user_security_qa_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "user_id" integer NOT NULL,
  "security_question_id" integer NOT NULL,
  "answer_hash" text NOT NULL
);

ALTER TABLE "passwords" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "sessions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "user_security_qs_as" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "user_security_qs_as" ADD FOREIGN KEY ("security_question_id") REFERENCES "lkp_security_questions" ("security_question_id") DEFERRABLE INITIALLY IMMEDIATE;
