CREATE TABLE "users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "email" text UNIQUE NOT NULL,
  "first_name" text NOT NULL,
  "last_name" text NOT NULL,
  "datetime_registered" timestamptz NOT NULL,
  "last_login" timestamptz
);

CREATE TABLE "passwords" (
  "password_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "user_id" integer NOT NULL,
  "salt" text NOT NULL,
  "password_hash" text NOT NULL,
  "password_last_updated" timestamptz
);

CREATE TABLE "sessions" (
  "session_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "user_id" integer NOT NULL,
  "login_time" timestamptz NOT NULL,
  "logout_time" timestamptz
);

CREATE TABLE "lkp_security_questions" (
  "security_question_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "security_question_text" text NOT NULL
);

CREATE TABLE "user_security_qs_as" (
  "user_security_qa_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "user_id" integer NOT NULL,
  "security_question_id" integer NOT NULL,
  "answer_hash" text NOT NULL
);

CREATE TABLE "uploads" (
  "upload_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "user_id" integer NOT NULL,
  "upload_descriptive_name" text NOT NULL,
  "upload_file_name" text NOT NULL,
  "upload_file_path" text NOT NULL,
  "uploaded_at" timestamptz NOT NULL
);

ALTER TABLE "passwords" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sessions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_security_qs_as" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_security_qs_as" ADD FOREIGN KEY ("security_question_id") REFERENCES "lkp_security_questions" ("security_question_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "uploads" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;
