CREATE TABLE "users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "email" text UNIQUE NOT NULL,
  "first_name" text NOT NULL,
  "middle_initial" char,
  "last_name" text NOT NULL,
  "datetime_registered" timestamptz NOT NULL,
  "last_login" timestamptz
);

CREATE TABLE "passwords" (
  "password_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "user_id" integer NOT NULL,
  "salt" text NOT NULL,
  "password_hash" text NOT NULL,
  "password_last_updated" timestamptz
);

CREATE TABLE "lkp_security_questions" (
  "security_question_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "security_question_text" text NOT NULL
);

CREATE TABLE "user_security_qs_as" (
  "user_security_qa_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "user_id" integer NOT NULL,
  "security_question_id" integer NOT NULL,
  "answer_hash" text NOT NULL
);

CREATE TABLE "uploads" (
  "upload_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "user_id" integer NOT NULL,
  "upload_descriptive_name" text NOT NULL,
  "upload_file_name" text NOT NULL,
  "upload_file_path" text NOT NULL,
  "uploaded_at" timestamptz NOT NULL
);

CREATE TABLE "applicant_profiles" (
  "applicant_profile_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "user_id" integer NOT NULL,
  "profile_last_updated" timestamptz,
  "is_missouri_resident" bool,
  "date_of_birth" date,
  "address_1" text,
  "address_2" text,
  "address_city" text,
  "address_state" text,
  "address_zipcode" text
);

CREATE TABLE "applicant_time_records" (
  "applicant_time_record_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "user_id" integer NOT NULL,
  "time_record_type_id" integer NOT NULL,
  "time_record_starting_datetime" timestamptz NOT NULL,
  "time_record_ending_datetime" timestamptz NOT NULL
);

CREATE TABLE "lkp_time_record_types" (
  "time_record_type_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "time_record_type" string NOT NULL
);

ALTER TABLE "applicant_time_records" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "applicant_time_records" ADD FOREIGN KEY ("time_record_type_id") REFERENCES "lkp_time_record_types" ("time_record_type_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "passwords" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_security_qs_as" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_security_qs_as" ADD FOREIGN KEY ("security_question_id") REFERENCES "lkp_security_questions" ("security_question_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "uploads" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "applicant_profiles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;
