--DROP TABLE IF EXISTS user_uploads;
--DROP TABLE IF EXISTS user_security_qs_as;
--DROP TABLE IF EXISTS lkp_security_questions;
--DROP TABLE IF EXISTS passwords;
--DROP TABLE IF EXISTS applicant_profile;
--DROP TABLE IF EXISTS users;


CREATE TABLE "users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "email" text UNIQUE NOT NULL,
  "first_name" text NOT NULL,
  "middle_initial" char,
  "last_name" text NOT NULL,
  "datetime_registered" timestamptz NOT NULL,
  "last_login" timestamptz
);

CREATE TABLE "passwords" (
  "password_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "user_id" integer NOT NULL,
  "salt" text NOT NULL,
  "password_hash" text NOT NULL,
  "password_last_updated" timestamptz
);

CREATE TABLE "lkp_security_questions" (
  "security_question_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "security_question_text" text NOT NULL
);

CREATE TABLE "user_security_qs_as" (
  "user_security_qa_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "user_id" integer NOT NULL,
  "security_question_id" integer NOT NULL,
  "answer_hash" text NOT NULL
);

CREATE TABLE "uploads" (
  "upload_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "user_id" integer NOT NULL,
  "upload_descriptive_name" text NOT NULL,
  "upload_file_name" text NOT NULL,
  "upload_file_path" text NOT NULL,
  "uploaded_at" timestamptz NOT NULL
);

CREATE TABLE "applicant_profile" (
  "applicant_profile_id" SERIAL PRIMARY KEY NOT NULL,
  "user_id" integer NOT NULL,
  "profile_last_updated" datetimetz,
  "is_missouri_resident" bool,
  "date_of_birth" date,
  "address_1" text,
  "address_2" text,
  "address_city" text,
  "address_state" text,
  "address_zipcode" text
);

ALTER TABLE "passwords" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_security_qs_as" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_security_qs_as" ADD FOREIGN KEY ("security_question_id") REFERENCES "lkp_security_questions" ("security_question_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "uploads" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "applicant_profile" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;
